### PR TITLE
Add notification System 

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #56 
Added notification toaster styem 

https://github.com/user-attachments/assets/4b7ba394-3816-4977-9e73-be78dae942c2

### CODE REVIEW

**Review by Devamani11D — APPROVED** [review]
Merging PR
🚀

**Comment by shubhagarwal1** [comment]
> Merging PR 🚀

Hey @Devamani11D please assign labels to the PR, this would be very helpful,

**Comment by shubhagarwal1** [comment]
Hey @Devamani11D i know you have been busy last days, can you please help me with putting labels on this PR, this would really help me.

**Comment by Devamani11D** [comment]
Yes sure

**Comment by shubhagarwal1** [comment]
Hey @Devamani11D i know you have been busy last days, can you please help me with putting labels on this PR, this would really help me.

**Pull request merged**
