### PR TITLE
Enhanced the structure of the file and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
## What does this PR do?

I have done little changes in structure like alignment and all and also added some new sections.

Changes I have done:-

1) Enhanced the structure of the code
2) Added Project flow chart
3) Added good ways to code
4) Added alternate way to contribute through GitHub desktop section

Fixes:[#45]

image

image

image

## How should this be tested?

I have checked through preview mode and without it thoroughly if there is any issue in alignment or anything else. I have not found any issue.

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Devamani11D — CHANGES_REQUESTED** [review]
Project structure is incorrect. Refer readme file, .github doesnt contain all those files.
And make flowchart in some online flowchart making site like draw.io
Remaining everything is fine

**Comment by milansamuel609** [comment]
> Project structure is incorrect. Refer readme file, .github doesnt contain all those files. And make flowchart in some online flowchart making site like draw.io Remaining everything is fine

Sure I will change the flowchart and its structure too.

**Comment by milansamuel609** [comment]
"I have added two remaning things from the structure that was run_in_localhost.js and video-thumbnail.png and also done some alignments in the structure to make it look more structured. I have not changed much. It is similar to the readme.md"

image

**Comment by Devamani11D** [comment]
Hey!
No need to keep 2 diagrams in the file and the first flowchart is incorrect. 
And No need to keep the same flowchart of PS in contribution file again. 
So , Remove those flowcharts and raise a PR with any other modifications you wanna add.
Thank you

**Comment by milansamuel609** [comment]
> Hey! No need to keep 2 diagrams in the file and the first flowchart is incorrect. And No need to keep the same flowchart of PS in contribution file again. So , Remove those flowcharts and raise a PR with any other modifications you wanna add. Thank you

I have added all other things that I want to add as I mention before. Just not able to add this one :(. I am sorry I am not able to do it properly. I will remove that flow diagram and PR again.

**Comment by milansamuel609** [comment]
I have done all the enhancements. Please kindly check it once.

**Comment by Devamani11D** [comment]
Can you please send ss of what changes you have done.I am not able to see

**Comment by milansamuel609** [comment]
> Can you please send ss of what changes you have done.I am not able to see

Changes I have done before :-

Enhanced the structure of the code
Added good ways to code
Added alternate way to contribute through GitHub desktop section

image

image

**Comment by milansamuel609** [comment]
I have done the changes. Please check them once. If they are ok please kindly merge the PR.

**Comment by milansamuel609** [comment]
Please kindly merge my PR if all the changes are fine. Also please attach the label for gssoc ext and level

**Comment by Devamani11D** [comment]
git clone https://github.com/<your-github-username>/FinVeda.git

I didn't understand this. 
Just give same project name

**Comment by milansamuel609** [comment]
I have fixed the changes. Please kindly check it once. If the changes are fine please kindly merge the PR. Also please attach the gssoc ext and level label.

**Comment by milansamuel609** [comment]
I have enhanced the file. Please kindly check the changes. If everything is fine please kindly merge and also add the gssoc extend and level label.

**Comment by milansamuel609** [comment]
@Devamani11D  Please kindly check the changes once if all the changes are fine please kindly merge this PR. Also please attach the gssoc extend and level label.

**Comment by milansamuel609** [comment]
@Devamani11D Please kindly merge the PR if all things are fine and also please add the label for gssoc extend and level also

**Review by Devamani11D — APPROVED** [review]
Merging , Thank you
But please have a look into the project when you are doing documentation for better understanding and easy merge.
🚀

**Comment by milansamuel609** [comment]
Please kindly add the gssoc extend and level label also

**Pull request merged**
