### PR TITLE
Character Length Validation for Username and Password

### LINKED ISSUE #35: Character Length Validation for Username and Password:
You could add validation to ensure that both the username and password meet a minimum character length before submission.

### PR DESCRIPTION
**Pull request by ananyag309**
## What does this PR do?

provides immediate feedback to the user if their input doesn't meet the minimum length requirements, improving the user experience and reducing the likelihood of invalid submissions.

Fixes #35 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Devamani11D — APPROVED** [review]
PR merged

**Comment by ananyag309** [comment]
@Devamani11D please add Gssoc label too

**Comment by Devamani11D** [comment]
It is in ext program

**Comment by Devamani11D** [comment]
So I didn't add gssoc label to any issue or pr

**Comment by ananyag309** [comment]
@Devamani11D I mean please add Gssoc ext label otherwise this pr points will not be reflected on leaderboard

**Pull request merged**
