### PR TITLE
Updated and Enhanced the readme.md

### LINKED ISSUE #1: Enhance Readme file
Hey, I think you could enhance your readme file. please assign this issue some label and assign it to me

### PR DESCRIPTION
**Pull request by Ayush07571**
Fixes #1 

Hey @Devamani11D , I raised a issue about enhancing the readme file and it was assigned to me. So here is my PR for updated readme files which is more attractive and explained a bit more which makes it user friendly.

I have also mentioned the project structure and flow of project as suggested by you and made some other changes.

I have attached screenshots of updated readme file for your reference.

Screenshot 2024-10-03 190735
Screenshot 2024-10-03 190821
Screenshot 2024-10-03 190813

Screenshot 2024-10-03 190831

### CODE REVIEW

**Comment by Devamani11D** [comment]
Mention the project structure of our current repo also, so that those who want to work on this can understand it better.
The starting point is cli.js and from there when we call different functions , it goes to different files. Better to make a flowchart like this.
flowchart
This is just for reference!!

**Comment by Ayush07571** [comment]
@Devamani11D please once check now and inform if it it correct or not?

**Comment by Devamani11D** [comment]
> @Devamani11D please once check now and inform if it it correct or not?

That's Cool @Ayush07571 .Thank you for being quick and clear.

**Comment by Ayush07571** [comment]
Thank You, enjoyed working on your project and thanks for your guidance and support. Would love to collaborate with you further.

**Comment by Ayush07571** [comment]
@Devamani11D  Can you please resolve this issue of hactoberfest

Screenshot 2024-10-04 170652

**Comment by Ayush07571** [comment]
one request please add the same labels to this PR which were assigned to the issue #1

**Comment by Devamani11D** [comment]
Done.Check it now!!

**Pull request merged**
